title: GitHub Pages Site Learning Experience
author: Nicolas Filippelli
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Creation of a GitHub Pages site

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  filippellinico # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
